languageCode = 'en-us'
defaultContentLanguage = "nl"
title = 'Beeldenrijk - Speltherapie en beeldende therapie'
theme = 'hugo-scroll'
baseUrl = 'http://beeldenrijk.nl/'

[params]

favicon = "images/favicon.png"
hidedesignbyline = true
